name: coffee_shop
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: any
  provider: ^6.0.5
  equatable: ^2.0.5
  fluttertoast: ^8.2.6
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  google_fonts: ^6.2.1


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/image/bg.png
    - assets/image/Black Coffee.png
    - assets/image/Espresso.png
    - assets/image/Latte.png
    - assets/image/coffee2.png
    - assets/image/cappuccino.png
    - assets/image/coffee.png
    - assets/image/visa.png
    - assets/image/wallet.png
    - assets/image/google.png
    - assets/image/amazon.png
    - assets/image/apple.png


#  fonts:
#    -assets/fonts/charlotte
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

